application: wwwdefontescom
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: root/favicon.ico
  upload: root/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: root/robots.txt

- url: /js
  static_dir: js

- url: /style
  static_dir: style

- url: /
  script: site/home.py

- url: /admin/.*
  script: site/admin.py
  login: admin
  
#- url: /.*
#  script: site/404.py
  
- url: /.*
  script: site/resources.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?.*/\.git/.*
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*Thumbs\.db$