application: wwwdefontescom
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1h"

handlers:
- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: root/favicon.ico
  upload: root/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: root/robots.txt

- url: /js
  static_dir: js

- url: /style
  static_dir: style

- url: /admin/.*
  script: app.admin.app
  login: admin
  
- url: /.*
  script: app.resources.app

libraries:
- name: django
  version: latest
  
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?.*/\.git/.*
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*Thumbs\.db$